service: todoist-serverless-lambda

provider:
  name: aws
  runtime: python3.6
  region: us-west-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
  dockerizePip: non-linux

functions:
  todoist_webhook:
    handler: handlers.todoist_handler.handle_event
    events:
      - http:
          path: /todoist/webhook
          method: post
    description: "Handle Todoist Webhooks Events"
    memorySize: 128
    timeout: 30
    environment:
      TODOIST_APIKEY: ${ssm.us-west-1:/TodoistApiKey~true}
      TODOIST_CLIENTSECRET: ${ssm.us-west-1:/TodoistClientsecret~true}