service: todoist-serverless-lambda

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

functions:
  todoist_webhook:
    handler: handler.handle_event
    description: "Handle Todoist Webhooks Events"
    memorySize: 128
    timeout: 60
    environment:
      TODOIST_APIKEY: ${ssm:/TodoistApiKey~true}
      TODOIST_CLIENTSECRET: $(ssm:/TodoistClientsecret~true}

