name: Deploy to AWS
on:
    push:
        branches: master
jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Set up Python 3.6
          uses: actions/setup-python@v2
          with:
            python-version: 3.6
        - name: Install Python Dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Set up Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x
        - name: Install Serverless via NPM
          run: npm install -g serverless@1.75.1
        - name: Install Python Requirements Plugin
          run: serverless plugin install --name serverless-python-requirements
        - name: Deploy with Serverless
          run: "serverless deploy --verbose"
          env:
            SLS_DEBUG: 1
